
import = [
"~/.config/alacritty/alacritty-theme.toml",
#"~/.config/alacritty/keybindings.toml",
]

[window]
opacity=0.85

[font]
normal = { family = "Cousine Nerd Font Mono", style = "Regular" }
bold = { family = "Cousine Nerd Font Mono", style = "Bold" }
italic = { family = "Cousine Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Cousine Nerd Font Mono", style = "Bold Italic" }

size=10.7
